/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmserver;

import db.Access;
import db.DBConnect;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.net.www.MimeTable;

/**
 *
 * @author Tran Quoc
 */
public class LichSuGD extends javax.swing.JFrame {

    /**
     * Creates new form LichSuGD
     */
    DefaultTableModel tableModel;
    public LichSuGD() {
        initComponents();
        setLocationRelativeTo(null);
        btnThoat.setIcon(new ImageIcon("src/images/quaylai.png"));
        btnLoc.setIcon(new ImageIcon("src/images/kiemtra.png"));
        btnLoc.setIcon(new ImageIcon("src/images/kiemtra.png"));
        tableModel = new DefaultTableModel();
        tableModel.addColumn("Số TK");
        tableModel.addColumn("Mã GD");
        tableModel.addColumn("Mã loại GD");
        tableModel.addColumn("Tên GD");
        tableModel.addColumn("Số Tiền");
        tableModel.addColumn("Ngày");
        tableModel.addColumn("Chú thích");
        tblHistory.setModel(tableModel);
        
        loadTable();
    }
    public void loadTable(){
        tableModel.setRowCount(0);
        
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getHistory}");
            rs = cstmt.executeQuery();
            while (rs.next()) {                
                Object[] dt ={
                    rs.getString("Sotaikhoan"),
                    rs.getString("Id"),
                    rs.getString("MaId"),
                    rs.getString("Reason"),
                    rs.getString("Sotien"),
                    rs.getString("Date"),
                    rs.getString("Content"),
                    
                };
                tableModel.addRow(dt);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
        DBConnect.closeAll(con, cstmt, rs);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtsotaikhoan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        btnLoc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Số Tài Khoản");

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Số Tài Khoản", "Ngày Tháng", "Số Tiền", "Lí Do"
            }
        ));
        jScrollPane2.setViewportView(tblHistory);

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(671, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtsotaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLoc)
                    .addComponent(txtsotaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.cancle();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        this.loc();
    }//GEN-LAST:event_btnLocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichSuGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichSuGD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtsotaikhoan;
    // End of variables declaration//GEN-END:variables

    private void cancle() {
        panel p = new panel();
        Access.CanleAcess(p, this);
    }

    private void loc() {
        String stk = txtsotaikhoan.getText();
        if (txtsotaikhoan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nhập Số Tài KHoản!!","THÔNG BÁO",JOptionPane.ERROR_MESSAGE);
        }else{
            Connection con = null;
            ResultSet rs = null;
            CallableStatement cstmt = null;
            con = DBConnect.opConnection();
            while (tableModel.getRowCount() > 0) {
                    tableModel.removeRow(0);
                }
            try {
                
                cstmt = con.prepareCall("{call getHistoryStk (?)}");
                cstmt.setString(1, stk);
                rs = cstmt.executeQuery();
                while (rs.next()) {                    
                    Object[] dt ={
                    rs.getString("Sotaikhoan"),
                    rs.getString("Id"),
                    rs.getString("MaId"),
                    rs.getString("Reason"),
                    rs.getString("Sotien"),
                    rs.getString("Date"),
                    rs.getString("Content"),
                    };
                    tableModel.addRow(dt);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(ThongTinKH.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                DBConnect.closeAll(con, cstmt, rs);
            }
        }
    }
}
