/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atmserver;

import com.sun.corba.se.impl.orbutil.ORBConstants;
import db.Access;
import db.DBConnect;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validate.untity;

/**
 *
 * @author Tran Quoc
 */
public class taikhoan extends javax.swing.JFrame {

    /**
     * Creates new form taikhoan
     */
    DefaultTableModel tableModel;
    public taikhoan() {
        initComponents();
        setLocationRelativeTo(null);
        
        btnEdit.setIcon(new ImageIcon("src/images/back.gif"));
        btxXoa.setIcon(new ImageIcon("src/images/xoa.png"));
        btxXoa1.setIcon(new ImageIcon("src/images/quaylai.png"));
        panel.setIcon(new ImageIcon("src/images/banner.png"));
        
        
        
        
    }
    public  void loadMaKH(String Sotaikhoan){
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId (?)}");           
            cstmt.setString(1,Sotaikhoan);
            rs = cstmt.executeQuery();
            while (rs.next()) {                
                MaKH.setText(Sotaikhoan);
                txtmatkhau.setText(rs.getString("Password"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(taikhoan.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            DBConnect.closeAll(con, cstmt, rs);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        MaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmatkhau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmkmoi = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btxXoa = new javax.swing.JButton();
        btxXoa1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtxacnhan = new javax.swing.JTextField();
        panel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sô TK");

        MaKH.setEditable(false);
        MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKHActionPerformed(evt);
            }
        });

        jLabel3.setText("Mật Khẩu Cũ");

        txtmatkhau.setEditable(false);

        jLabel4.setText("Mật Khẩu Mới");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btxXoa.setText("Xóa");

        btxXoa1.setText("Quay Lại");
        btxXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btxXoa1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Xác Nhận MK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btxXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btxXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtxacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btxXoa)
                    .addComponent(btxXoa1))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btxXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btxXoa1ActionPerformed
        // TODO add your handling code here:
        this.cancle();
    }//GEN-LAST:event_btxXoa1ActionPerformed

    private void MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String loi="";
        String password = txtmkmoi.getText();
        String repassword = txtxacnhan.getText();
        // validate..............
        if (password.length()==0 && repassword.length()==0) {
            loi+="\n Mật khẩu Hoặc xác nhận mật khẩu không được để trống!!";
        }else{
            if(!password.equals(repassword)){
            loi+="\n Xác nhận mật khẩu không chính xác";
        }
            else if (!untity.checkPass(txtmkmoi.getText())) {
                loi+="\n Mật khẩu phải là số và chỉ được 6 kí tự!!!";
            }
        }
        if (loi.length()==0) {
            Connection con = null;
            ResultSet rs = null;
            CallableStatement cstmt = null;
            con = DBConnect.opConnection();
            try {
                cstmt = con.prepareCall("{call updatePass (?,?)}");
                cstmt.setString(1, MaKH.getText());
                cstmt.setString(2, txtmkmoi.getText());
                int i = cstmt.executeUpdate();
                if (i>0) {
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công");
                    ThongTinKH tt = new ThongTinKH();
                    Access.CanleAcess(tt, this);
                }else{
                    JOptionPane.showMessageDialog(null, "Đổi mật khẩu thất bại!!!","THÔNG BÁO",JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(taikhoan.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                DBConnect.closeAll(con, cstmt, rs);
            }
        }else{
            JOptionPane.showMessageDialog(null, loi);
        }
        
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taikhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taikhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MaKH;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btxXoa;
    private javax.swing.JButton btxXoa1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel panel;
    private javax.swing.JTextField txtmatkhau;
    private javax.swing.JTextField txtmkmoi;
    private javax.swing.JTextField txtxacnhan;
    // End of variables declaration//GEN-END:variables

    private void cancle() {
        ThongTinKH tt = new ThongTinKH();
        Access.CanleAcess(tt, this);
    }
}
