/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_java;

import db.Access;
import db.DBConnect;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import validate.untity;

/**
 *
 * @author Tran Quoc
 */
public class frmRutTien2 extends javax.swing.JFrame {

    /**
     * Creates new form frmRutTien2
     */
    public String stk = "";

    public frmRutTien2() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(630, 500);

        banner.setIcon(new ImageIcon("src/images/banner.png"));
        btnYES.setIcon(new ImageIcon("src/images/thuchien.png"));
        btnNo.setIcon(new ImageIcon("src/images/exit.png"));
        btnRutTien.setIcon(new ImageIcon("src/images/tru.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnYES = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        banner = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtnhapsotien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnRutTien = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSTK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnYES.setText("Quay lại");
        btnYES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYESActionPerformed(evt);
            }
        });

        btnNo.setText("Cancle");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập Số Tiền ");

        txtnhapsotien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnhapsotienActionPerformed(evt);
            }
        });

        jLabel2.setText("VNĐ");

        btnRutTien.setText("Rút Tiền");
        btnRutTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutTienActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("50.000");

        jLabel4.setText("Số Tiền Tối Thiểu");

        jLabel3.setText("Số TK:");

        txtSTK.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(btnYES)
                                .addGap(39, 39, 39)
                                .addComponent(btnNo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtnhapsotien, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(38, 38, 38)
                                        .addComponent(btnRutTien))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtSTK, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnhapsotien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnRutTien))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnYES)
                    .addComponent(btnNo))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYESActionPerformed

        stk = txtSTK.getText();
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId (?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            if (rs.next()) {
                this.Cancle();

            }
            //
            //
            //
            //
        } catch (SQLException ex) {
            Logger.getLogger(giaodien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnYESActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        nhapSTK stk = new nhapSTK();
        stk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnRutTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutTienActionPerformed

        Date day = null;
        stk = txtSTK.getText();
        String ruttien = txtnhapsotien.getText();
        float sotienrut = 0;
        float tongtien = 0;

        if (ruttien.length() == 0 && !untity.checkTien(txtnhapsotien.getText())) {
            JOptionPane.showMessageDialog(null, "Lỗi", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
        } else {
            sotienrut = Float.parseFloat(txtnhapsotien.getText());
            if (sotienrut < 50000) {
                JOptionPane.showMessageDialog(null, "Số tiền rút phải lớn hơn 50000", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            } else if (sotienrut > 5000000) {
                JOptionPane.showMessageDialog(null, "Số tiền rút quá lớn", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            } else if (sotienrut % 50000 != 0) {
                JOptionPane.showMessageDialog(null, "Số tiền không hợp lệ", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
            } else {
                Connection con = null;
                ResultSet rs = null;
                CallableStatement cstmt = null;
                con = DBConnect.opConnection();
                try {
                    cstmt = con.prepareCall("{call getCustomerId(?)}");
                    cstmt.setString(1, stk);
                    rs = cstmt.executeQuery();
                    while (rs.next()) {
                        cstmt = con.prepareCall("{call getCustomer}");
                        tongtien = rs.getFloat("Money");
                        sotienrut = Float.parseFloat(txtnhapsotien.getText());
                        tongtien = tongtien - sotienrut;
                        if (tongtien >= 50000) {
                            cstmt = con.prepareCall("{call updateMoney(?,?)}");
                            cstmt.setString(1, txtSTK.getText());
                            cstmt.setFloat(2, tongtien);
                            int i = cstmt.executeUpdate();
                            if (i > 0) {
                                JOptionPane.showMessageDialog(null, "Rút iền thành công");
                                //  tien hanh lap bien lai
                                cstmt = con.prepareCall("{call insertHistory (?,?,?,?)}");
                                cstmt.setInt(1, 3);
                                cstmt.setString(2, stk);

                                cstmt.setDate(3, day);
                                cstmt.setString(4, txtnhapsotien.getText());
                                int k = cstmt.executeUpdate();
                                if (k > 0) {
                                    if (JOptionPane.showConfirmDialog(null, "Bạn muốn nhận biên lai", "", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                                        cstmt = con.prepareCall("{call getHistory}");
                                        rs = cstmt.executeQuery();
                                        while (rs.next()) {
                                            Object[] dt = {
                                                rs.getString("Sotaikhoan"),
                                                rs.getString("Id"),
                                                rs.getString("MaId"),
                                                rs.getString("Reason"),
                                                rs.getString("Sotien"),
                                                rs.getString("Date"),
                                                rs.getString("Content"),};
                                            ObjectOutputStream ghi = null;
                                            try {
                                                ghi = new ObjectOutputStream(new FileOutputStream("src/data/bienlai.txt"));
                                                ghi.writeObject(dt);
                                            } catch (IOException ex) {
                                                Logger.getLogger(ruttien.class.getName()).log(Level.SEVERE, null, ex);
                                            } finally {
                                                try {
                                                    ghi.close();
                                                } catch (IOException ex) {
                                                    Logger.getLogger(ruttien.class.getName()).log(Level.SEVERE, null, ex);
                                                }
                                            }

                                        }
                                    } else {
                                    }

                                    giaodien gd = new giaodien();
                                    gd.loadName(stk);
                                    Access.CanleAcess(gd, this);
                                }
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "SỐ tiền trong tài khoản không đủ", "THÔNG BÁO", JOptionPane.ERROR_MESSAGE);
                            giaodien gd = new giaodien();
                            gd.loadName(stk);
                            Access.CanleAcess(gd, this);
                        }

                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Rút tiền không thành công!!!", "LOI", JOptionPane.ERROR_MESSAGE);
                } finally {
                    DBConnect.closeAll(con, cstmt, rs);
                }

            }
        }


    }//GEN-LAST:event_btnRutTienActionPerformed

    private void txtnhapsotienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnhapsotienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnhapsotienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRutTien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRutTien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRutTien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRutTien2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRutTien2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnRutTien;
    private javax.swing.JButton btnYES;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtSTK;
    private javax.swing.JTextField txtnhapsotien;
    // End of variables declaration//GEN-END:variables

    private void Cancle() {
        ruttien rt = new ruttien();
        rt.loadrt(stk);
        Access.CanleAcess(rt, this);
    }

    public void loadrt2(String stk) {
        Connection con = null;
        ResultSet rs = null;
        CallableStatement cstmt = null;
        con = DBConnect.opConnection();
        try {
            cstmt = con.prepareCall("{call getCustomerId(?)}");
            cstmt.setString(1, stk);
            rs = cstmt.executeQuery();
            while (rs.next()) {
                cstmt = con.prepareCall("{call getCustomer}");
                txtSTK.setText(stk);

            }
        } catch (SQLException ex) {
            Logger.getLogger(dangnhapATM.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            DBConnect.closeAll(con, cstmt, rs);
        }
    }
}
